"""base-7 (renaming)

Revision ID: 107fe30cd4aa
Revises: d5f9f08d85d2
Create Date: 2025-07-13 10:44:40.218751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '107fe30cd4aa'
down_revision: Union[str, None] = 'd5f9f08d85d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('original_url', sa.String(), nullable=False))
    op.add_column('links', sa.Column('short_code', sa.String(), nullable=False))
    op.drop_constraint(op.f('links_short_link_key'), 'links', type_='unique')
    op.create_unique_constraint(None, 'links', ['short_code'])
    op.drop_column('links', 'entry_link')
    op.drop_column('links', 'short_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('short_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('links', sa.Column('entry_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'links', type_='unique')
    op.create_unique_constraint(op.f('links_short_link_key'), 'links', ['short_link'], postgresql_nulls_not_distinct=False)
    op.drop_column('links', 'short_code')
    op.drop_column('links', 'original_url')
    # ### end Alembic commands ###
