"""base-6

Revision ID: d5f9f08d85d2
Revises: fd07edc3e4d8
Create Date: 2025-06-16 17:19:38.595554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f9f08d85d2'
down_revision: Union[str, None] = 'fd07edc3e4d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('links_user_id_fkey'), 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(op.f('links_user_id_fkey'), 'links', 'users', ['user_id'], ['user_id'])
    op.drop_column('links', 'name')
    # ### end Alembic commands ###
