class IUnitOfWork:
    async def start_pipeline(self): ...

    async def execute_pipeline(self): ...

    async def discard_pipeline(self): ...

    async def clear_cache(self, pattern: str = "*"): ...

    async def get_cache_info(self) -> dict: ...

    async def __aenter__(self):
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb): ...
