"""base-6

Revision ID: 20cd42d8796c
Revises: 6ef5a333a058
Create Date: 2025-06-16 17:20:28.024497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20cd42d8796c'
down_revision: Union[str, None] = '6ef5a333a058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('name', sa.String(), nullable=False))
    op.drop_constraint(op.f('links_user_id_fkey'), 'links', type_='foreignkey')
    op.create_foreign_key(None, 'links', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.create_foreign_key(op.f('links_user_id_fkey'), 'links', 'users', ['user_id'], ['user_id'])
    op.drop_column('links', 'name')
    # ### end Alembic commands ###
